language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
env:
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.12
  - DJANGO_VERSION=3.2.15
  - DJANGO_VERSION=4.0.7
# https://docs.djangoproject.com/en/stable/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - env: DJANGO_VERSION=2.1.15
      python: 3.8
    - env: DJANGO_VERSION=2.1.15
      python: 3.9
    - env: DJANGO_VERSION=3.2.15
      python: 3.5
    - env: DJANGO_VERSION=4.0.7
      python: 3.5
    - env: DJANGO_VERSION=4.0.7
      python: 3.6
    - env: DJANGO_VERSION=4.0.7
      python: 3.7
addons:
  apt_packages:
    - pandoc
before_install:
  - ./pypi_packager.sh
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U importlib_metadata; fi
  - pip install -q django==$DJANGO_VERSION
  - pip install -e .[coverage]
  - pip install -q coveralls
script:
  - coverage run --source=constrainedfilefield constrainedfilefield/tests/__main__.py
after_success:
  - coveralls
